
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
    readSidebar:[{ type: 'autogenerated', dirName: 'read'}],
    eKYCSidebar: [{ type: 'autogenerated', dirName: 'ekyc' }],
    // readSidebar: [
    //     {
    //         type: 'category',
    //         label: 'FPT AI Read Documentation',
    //         items: [
    //             'read/intro',
    //             {
    //                 type: 'html',
    //                 value: 'I. Intelligent Document Processing (IDP) Introduction',
    //                 className: 'sidebar-title',
    //             },
    //             'read/idp-documentation/what-is-idp',
    //             'read/idp-documentation/idp-purpose',
    //             'read/idp-documentation/benefit-ai-reader',
    //             'read/idp-documentation/start-fpt-ai',
    //             {
    //                 type: 'html',
    //                 value: 'II. FPT.AI Reader Platform',
    //                 className: 'sidebar-title',
    //             },
    //             'read/todo',
    //         ],
    //     },
    // ],

    // eKYCSidebar: [
    //     {
    //         type: 'category',
    //         label: 'FPT AI eKYC Documentation',
    //         items: [
    //             'ekyc/intro',
    //             {
    //                 type: 'html',
    //                 value: 'I. FPT AI eKYC Introduction',
    //                 className: 'sidebar-title',
    //             },
    //             'ekyc/introduction/what-is-ekyc',
    //             'ekyc/introduction/benefit-ai-ekyc',
    //             'ekyc/introduction/start-with-fpt-ai-ekyc',
    //             {
    //                 type: 'html',
    //                 value: 'II. Integration with FPT AI eKYC',
    //                 className: 'sidebar-title',
    //             },
    //             {
    //                 type: 'html',
    //                 value: 'III. Tutorials',
    //                 className: 'sidebar-title',
    //             },
    //         ],
    //         collapsible: true,
    //         collapsed: false,

    //     },
    // ],
};

module.exports = sidebars;
